<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Idempotency\Core.Idempotency.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CoreSystem.Redis" />
	</ItemGroup>

</Project>