<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core.Idempotency.PostgreSql\Core.Idempotency.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\Core.Idempotency.Redis\Core.Idempotency.Redis.csproj" />
  </ItemGroup>

</Project>
