<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>CoreSystem.Idempotency</PackageId>
	<Version>1.0.4</Version>
	<AssemblyVersion>1.0.4</AssemblyVersion>
	<FileVersion>1.0.4.0</FileVersion>
	<InformationalVersion>1.0.4</InformationalVersion>
	<Authors>Federin Pastor Gutierrez Ortiz</Authors>
	<Description>
		Production-ready idempotency framework for ASP.NET Core that guarantees exactly-once request processing with Redis and PostgreSQL providers, request fingerprinting, response replay, and native OpenTelemetry support.
	</Description>
	<RepositoryUrl>https://github.com/FEDERIN/CoreSystem</RepositoryUrl>
	<PackageProjectUrl>https://federin.github.io/CoreSystem/Idempotency</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageTags>
		Idempotency;
		ASP.NET Core;
		Middleware;
		Distributed Systems;
		Exactly Once;
		Redis;
		PostgreSQL;
		OpenTelemetry;
		Observability;
		Cloud Native
	</PackageTags>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="CoreSystem.Http" />
    <PackageReference Include="CoreSystem.Observability.Abstractions" />
    <PackageReference Include="CoreSystem.Redis" />
    <PackageReference Include="CoreSystem.Serialization" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
	<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
	  <None Include="LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
	
 <ItemGroup>
	 <InternalsVisibleTo Include="Core.Idempotency.UnitTests" />
	 <InternalsVisibleTo Include="Core.Idempotency.IntegrationTests" />
	 <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
 </ItemGroup>
	
 <ItemGroup>
   <Folder Include="Internal\Capture\" />
 </ItemGroup>
</Project>
