<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Cache\Core.Cache.csproj" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Core.Cache.Rehydration.UnitTests" />
	<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>

