<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>CoreSystem.Resilience</PackageId>
		<Version>2.0.0</Version>
		<AssemblyVersion>2.0.0</AssemblyVersion>
		<FileVersion>2.0.0.0</FileVersion>
		<InformationalVersion>2.0.0</InformationalVersion>
		<Authors>Federin Pastor Gutierrez Ortiz</Authors>
		<Description>
			Production-ready resilience framework for .NET 8 with configurable resilience pipelines, Retry, Timeout, Circuit Breaker, and OpenTelemetry metrics.
		</Description>
		<RepositoryUrl>https://github.com/FEDERIN/CoreSystem</RepositoryUrl>
		<PackageProjectUrl>https://federin.github.io/CoreSystem/Resilience</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<RepositoryType>git</RepositoryType>
		<PackageTags>
			Resilience;
			Retry;
			Timeout;
			CircuitBreaker;
			Polly;
			OpenTelemetry;
			Metrics;
			DependencyInjection;
			CloudNative;
			.NET8
		</PackageTags>
		<PackageReleaseNotes>
			Resilience pipelines with Retry, Timeout, Circuit Breaker, Dependency Injection, and OpenTelemetry metrics.
		</PackageReleaseNotes>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CoreSystem.Observability.Abstractions" />
    <PackageReference Include="Polly" />
	<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>
	
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>

	  <None Include="README.md" Pack="true" PackagePath="\" />
	  <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Core.Resilience.UnitTests" />
	<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
