using Core.Http.Responses;
using Microsoft.AspNetCore.Http;

namespace Core.Http.Abstractions;

/// <summary>
/// Defines a contract for capturing an HTTP response generated by the request pipeline.
/// </summary>
public interface IResponseCapture
{
    /// <summary>
    /// Executes the request pipeline and captures the resulting HTTP response.
    /// </summary>
    /// <param name="context">
    /// The current HTTP context.
    /// </param>
    /// <param name="next">
    /// The delegate that represents the next middleware in the request pipeline.
    /// </param>
    /// <param name="cancellationToken">
    /// A token used to cancel the execution.
    /// </param>
    /// <returns>
    /// A <see cref="CapturedResponse"/> containing the captured response body,
    /// status code, and headers.
    /// </returns>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "'next' matches ASP.NET Core middleware conventions and renaming would break named-argument callers.")]
    Task<CapturedResponse> CaptureAsync(
        HttpContext context,
        RequestDelegate next,
        CancellationToken cancellationToken = default);
}