using Core.Http.Responses;
using Microsoft.AspNetCore.Http;

namespace Core.Http.Abstractions;

/// <summary>
/// Defines a contract for capturing an HTTP response generated by the request pipeline.
/// </summary>
public interface IResponseCapture
{
    /// <summary>
    /// Executes the request pipeline and captures the resulting HTTP response.
    /// </summary>
    /// <param name="context">
    /// The current HTTP context.
    /// </param>
    /// <param name="next">
    /// The delegate that represents the next middleware in the request pipeline.
    /// </param>
    /// <returns>
    /// A <see cref="CapturedResponse"/> containing the captured response body,
    /// status code, and headers.
    /// </returns>
    Task<CapturedResponse> CaptureAsync(
        HttpContext context,
        RequestDelegate next);
}