<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Dapper" />
	  <PackageReference Include="Npgsql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Idempotency\Core.Idempotency.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Core.Idempotency.PostgreSql.UnitTests" />
		<InternalsVisibleTo Include="Core.Idempotency.PostgreSql.IntegrationTests" />
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
	</ItemGroup>
</Project>